services:

  employees-service:
    image: employees-service:latest
    container_name: employees-service
    build:
      context: .
      dockerfile: ./src/services/EmployeesService/EmployeesService.App/Dockerfile
    environment:
      - MessageBroker__Host=amqp://rabbit-mq:5672
      - MessageBroker__Username=developer
      - MessageBroker__Password=developer123!
      - ConnectionStrings__DefaultConnection=Host=employees-service-database;Port=5432;Database=employees;Username=developer;Password=developer123!
      - ASPNETCORE_URLS=http://+:5000
      - ASPNETCORE_ENVIRONMENT=Development
      - DOTNET_RUNNING_IN_CONTAINER=true
    expose:
      - 5000
    ports:
      - "5000:5000"
    depends_on:
      employees-service-database:
        condition: service_healthy
      rabbit-mq:
        condition: service_healthy

  task-manager-service:
    image: task-manager-service:latest
    container_name: task-manager-service
    build: 
      context: .
      dockerfile: ./src/services/TaskManagementService/TaskManagmentService.App/Dockerfile
    environment:
      - MessageBroker__Host=amqp://rabbit-mq:5672
      - MessageBroker__Username=developer
      - MessageBroker__Password=developer123!
      - ConnectionStrings__DefaultConnection=Host=task-manager-service-database;Port=5432;Database=assignments;Username=developer;Password=developer123!
      - DOTNET_RUNNING_IN_CONTAINER=true
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:5001
    expose:
      - 5001
    ports:
      - "5001:5001"
    depends_on:
      task-manager-service-database:
        condition: service_healthy
      rabbit-mq:
        condition: service_healthy
        
  project-manager-service:
    image: project-manager-service:latest
    container_name: project-manager-service
    build: 
      context: .
      dockerfile: ./src/services/ProjectManagementService/ProjectManagementService.App/Dockerfile
    environment:
      - MessageBroker__Host=amqp://rabbit-mq:5672
      - MessageBroker__Username=developer
      - MessageBroker__Password=developer123!
      - ConnectionStrings__DefaultConnection=Host=project-manager-service-database;Port=5432;Database=projects;Username=developer;Password=developer123!
      - DOTNET_RUNNING_IN_CONTAINER=true
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:5002
    expose:
      - 5002
    ports:
      - "5002:5002"
    depends_on:
      project-manager-service-database:
        condition: service_healthy
      rabbit-mq:
        condition: service_healthy
    
  assignment-group-manager-service:
    image: assignment-group-manager-service:latest
    container_name: assignment-group-manager-service
    build: 
      context: .
      dockerfile: ./src/services/AssignmentGroupManagemetService/AssignmentGroupManagemetService.App/Dockerfile
    environment:
      - MessageBroker__Host=amqp://rabbit-mq:5672
      - MessageBroker__Username=developer
      - MessageBroker__Password=developer123!
      - ConnectionStrings__DefaultConnection=Host=assignment-group-manager-service-database;Port=5432;Database=assignment-groups;Username=developer;Password=developer123!
      - DOTNET_RUNNING_IN_CONTAINER=true
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:5003
    expose:
      - 5003
    ports:
      - "5003:5003"
    depends_on:
      assignment-group-manager-service-database:
        condition: service_healthy
      rabbit-mq:
        condition: service_healthy

  employees-service-database:
    image: postgres:latest
    container_name: employees-service-database
    environment:
      - POSTGRES_USER=developer
      - POSTGRES_DB=employees
      - POSTGRES_PASSWORD=developer123!
    volumes:
      - employees-service:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U developer -d employees"]
      interval: 10s
      timeout: 20s
      retries: 5
      start_period: 20s

  task-manager-service-database:
    image: postgres:latest
    container_name: task-manager-service-database
    environment:
      - POSTGRES_USER=developer
      - POSTGRES_DB=assignments
      - POSTGRES_PASSWORD=developer123!
    volumes:
      - task-manager-service:/var/lib/postgresql/data/
    ports:
      - "5433:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U developer -d assignments"]
      interval: 10s
      timeout: 20s
      retries: 5
      start_period: 20s

  project-manager-service-database:
    image: postgres:latest
    container_name: project-manager-service-database
    environment:
      - POSTGRES_USER=developer
      - POSTGRES_DB=projects
      - POSTGRES_PASSWORD=developer123!
    volumes:
      - project-manager-service:/var/lib/postgresql/data/
    ports:
      - "5434:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U developer -d projects"]
      interval: 10s
      timeout: 20s
      retries: 5
      start_period: 20s

  assignment-group-manager-service-database:
    image: postgres:latest
    container_name: assignment-group-manager-service-database
    environment:
      - POSTGRES_USER=developer
      - POSTGRES_DB=assignment-groups
      - POSTGRES_PASSWORD=developer123!
    volumes:
      - assignment-groups-manager-service:/var/lib/postgresql/data/
    ports:
      - "5435:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U developer -d assignment-groups"]
      interval: 10s
      timeout: 20s
      retries: 5
      start_period: 20s

  rabbit-mq:
    image: rabbitmq:management
    environment:
      - RABBITMQ_DEFAULT_USER=developer
      - RABBITMQ_DEFAULT_PASS=developer123!
    volumes:
      - rabbit-mq-data:/var/lib/rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    healthcheck:
      test: rabbitmq-diagnostics -q ping
      interval: 10s
      timeout: 10s
      retries: 3
  
volumes:
  employees-service: 
  task-manager-service:
  project-manager-service:
  assignment-groups-manager-service:
  rabbit-mq-data: